import { Space } from './types';

export const board: Space[] = [
  { id: 0, name: 'GO', kind: 'go' },
  { id: 1, name: 'Mediterranean Ave', kind: 'property', price: 60, rent: 2, color: '#7a4a2a' },
  { id: 2, name: 'Community Chest', kind: 'community' },
  { id: 3, name: 'Baltic Ave', kind: 'property', price: 60, rent: 4, color: '#7a4a2a' },
  { id: 4, name: 'Income Tax', kind: 'tax' },
  { id: 5, name: 'Reading Railroad', kind: 'railroad', price: 200, rent: 25 },
  { id: 6, name: 'Oriental Ave', kind: 'property', price: 100, rent: 6, color: '#9bd3f5' },
  { id: 7, name: 'Chance', kind: 'chance' },
  { id: 8, name: 'Vermont Ave', kind: 'property', price: 100, rent: 6, color: '#9bd3f5' },
  { id: 9, name: 'Connecticut Ave', kind: 'property', price: 120, rent: 8, color: '#9bd3f5' },
  { id: 10, name: 'Jail / Just Visiting', kind: 'jail' },
  { id: 11, name: 'St. Charles Place', kind: 'property', price: 140, rent: 10, color: '#c754b8' },
  { id: 12, name: 'Electric Company', kind: 'utility', price: 150, rent: 12 },
  { id: 13, name: 'States Ave', kind: 'property', price: 140, rent: 10, color: '#c754b8' },
  { id: 14, name: 'Virginia Ave', kind: 'property', price: 160, rent: 12, color: '#c754b8' },
  { id: 15, name: 'Pennsylvania Railroad', kind: 'railroad', price: 200, rent: 25 },
  { id: 16, name: 'St. James Place', kind: 'property', price: 180, rent: 14, color: '#e98937' },
  { id: 17, name: 'Community Chest', kind: 'community' },
  { id: 18, name: 'Tennessee Ave', kind: 'property', price: 180, rent: 14, color: '#e98937' },
  { id: 19, name: 'New York Ave', kind: 'property', price: 200, rent: 16, color: '#e98937' },
  { id: 20, name: 'Free Parking', kind: 'free' },
  { id: 21, name: 'Kentucky Ave', kind: 'property', price: 220, rent: 18, color: '#d73b3e' },
  { id: 22, name: 'Chance', kind: 'chance' },
  { id: 23, name: 'Indiana Ave', kind: 'property', price: 220, rent: 18, color: '#d73b3e' },
  { id: 24, name: 'Illinois Ave', kind: 'property', price: 240, rent: 20, color: '#d73b3e' },
  { id: 25, name: 'B. & O. Railroad', kind: 'railroad', price: 200, rent: 25 },
  { id: 26, name: 'Atlantic Ave', kind: 'property', price: 260, rent: 22, color: '#f4d44d' },
  { id: 27, name: 'Ventnor Ave', kind: 'property', price: 260, rent: 22, color: '#f4d44d' },
  { id: 28, name: 'Water Works', kind: 'utility', price: 150, rent: 12 },
  { id: 29, name: 'Marvin Gardens', kind: 'property', price: 280, rent: 24, color: '#f4d44d' },
  { id: 30, name: 'Go To Jail', kind: 'goToJail' },
  { id: 31, name: 'Pacific Ave', kind: 'property', price: 300, rent: 26, color: '#45a86f' },
  { id: 32, name: 'North Carolina Ave', kind: 'property', price: 300, rent: 26, color: '#45a86f' },
  { id: 33, name: 'Community Chest', kind: 'community' },
  { id: 34, name: 'Pennsylvania Ave', kind: 'property', price: 320, rent: 28, color: '#45a86f' },
  { id: 35, name: 'Short Line', kind: 'railroad', price: 200, rent: 25 },
  { id: 36, name: 'Chance', kind: 'chance' },
  { id: 37, name: 'Park Place', kind: 'property', price: 350, rent: 35, color: '#3f6fb5' },
  { id: 38, name: 'Luxury Tax', kind: 'tax' },
  { id: 39, name: 'Boardwalk', kind: 'property', price: 400, rent: 50, color: '#3f6fb5' }
];

export const cornerIds = new Set([0, 10, 20, 30]);
