import { handleApi, handleRoomAction } from "../../../../../lib/api";
import {
  addKillerBunniesComputer,
  anteKillerBunniesRoomPovertyPoker,
  buyKillerBunniesRoomShopItem,
  callKillerBunniesRoomPovertyPoker,
  chooseKillerBunniesRoomAuctionTarget,
  chooseKillerBunniesRoomBlackCatTarget,
  chooseKillerBunniesRoomBunnyExchangeGive,
  chooseKillerBunniesSpecialRoom,
  chooseKillerBunniesRoomCarrot,
  chooseKillerBunniesRoomBlueRollTarget,
  chooseKillerBunniesRoomDefectorTarget,
  chooseKillerBunniesRoomEveryoneFeedBunny,
  chooseKillerBunniesRoomMisfortuneTarget,
  chooseKillerBunniesRoomModifierTarget,
  chooseKillerBunniesRoomNumber,
  chooseKillerBunniesRoomPlayerTarget,
  chooseKillerBunniesRoomRevivedBunny,
  chooseKillerBunniesRoomRoamingTarget,
  chooseKillerBunniesRoomUtilityBunnyTarget,
  drawKillerBunniesRoomPile,
  discardKillerBunniesRoomDefectorDetector,
  discardKillerBunniesRoomBlackCatClover,
  discardExtraKillerBunniesRoomCard,
  donateKillerBunniesRoomBounty,
  getKillerBunniesRoom,
  joinKillerBunniesRoom,
  playKillerBunniesTopRun,
  playSavedKillerBunniesRoomSpecial,
  placeKillerBunniesRoomAuctionBid,
  placeKillerBunniesRoomBlackCatClover,
  removeKillerBunniesComputer,
  replaceKillerBunniesRoomRun,
  resolveKillerBunniesRoomDefense,
  resolveKillerBunniesRoomWeaponReuse,
  resolveKillerBunniesRoomAreaWeaponRoll,
  resolveKillerBunniesRoomBlackCatRoll,
  resolveKillerBunniesRoomBlueCardRoll,
  resolveKillerBunniesRoomBlueSpecialRoll,
  resolveKillerBunniesRoomBunnyExchange,
  resolveKillerBunniesRoomCardDiceRoll,
  resolveKillerBunniesRoomCardAction,
  resolveKillerBunniesRoomRoamingRoll,
  resolveKillerBunniesRoomDefectorRoll,
  resolveKillerBunniesRoomImmediateCard,
  resolveKillerBunniesRoomManualCard,
  resolveKillerBunniesRoomPovertyPokerRoll,
  setKillerBunniesExpansions,
  startKillerBunniesRoom,
  targetKillerBunniesBunny,
  chooseInitialKillerBunniesRoomRun,
} from "../../../../../lib/killer-bunnies-rooms";

export async function GET(request, context) {
  const { code } = await context.params;
  const token = new URL(request.url).searchParams.get("token") || "";
  return handleApi(async () => getKillerBunniesRoom({ roomCode: code, token }));
}

export async function POST(request, context) {
  const { code } = await context.params;
  return handleRoomAction(request, code, {
    join: joinKillerBunniesRoom,
    addComputer: addKillerBunniesComputer,
    removeComputer: removeKillerBunniesComputer,
    setExpansions: setKillerBunniesExpansions,
    start: startKillerBunniesRoom,
    chooseInitialRun: chooseInitialKillerBunniesRoomRun,
    playTopRun: playKillerBunniesTopRun,
    specialChoice: chooseKillerBunniesSpecialRoom,
    playSaved: playSavedKillerBunniesRoomSpecial,
    targetBunny: targetKillerBunniesBunny,
    chooseEveryoneFeedBunny: chooseKillerBunniesRoomEveryoneFeedBunny,
    chooseAuctionTarget: chooseKillerBunniesRoomAuctionTarget,
    chooseBlackCatTarget: chooseKillerBunniesRoomBlackCatTarget,
    resolveBlackCatRoll: resolveKillerBunniesRoomBlackCatRoll,
    placeBlackCatClover: placeKillerBunniesRoomBlackCatClover,
    discardBlackCatClover: discardKillerBunniesRoomBlackCatClover,
    placeAuctionBid: placeKillerBunniesRoomAuctionBid,
    chooseBunnyExchangeGive: chooseKillerBunniesRoomBunnyExchangeGive,
    resolveBunnyExchange: resolveKillerBunniesRoomBunnyExchange,
    resolveDefense: resolveKillerBunniesRoomDefense,
    resolveWeaponReuse: resolveKillerBunniesRoomWeaponReuse,
    resolveAreaWeaponRoll: resolveKillerBunniesRoomAreaWeaponRoll,
    chooseBlueRollTarget: chooseKillerBunniesRoomBlueRollTarget,
    resolveBlueCardRoll: resolveKillerBunniesRoomBlueCardRoll,
    chooseNumber: chooseKillerBunniesRoomNumber,
    resolveBlueSpecialRoll: resolveKillerBunniesRoomBlueSpecialRoll,
    resolveCardDiceRoll: resolveKillerBunniesRoomCardDiceRoll,
    resolveCardAction: resolveKillerBunniesRoomCardAction,
    donateBounty: donateKillerBunniesRoomBounty,
    chooseRevivedBunny: chooseKillerBunniesRoomRevivedBunny,
    chooseRoamingTarget: chooseKillerBunniesRoomRoamingTarget,
    resolveRoamingRoll: resolveKillerBunniesRoomRoamingRoll,
    resolveManualCard: resolveKillerBunniesRoomManualCard,
    resolveImmediateCard: resolveKillerBunniesRoomImmediateCard,
    chooseMisfortuneTarget: chooseKillerBunniesRoomMisfortuneTarget,
    chooseModifierTarget: chooseKillerBunniesRoomModifierTarget,
    choosePlayerTarget: chooseKillerBunniesRoomPlayerTarget,
    chooseUtilityBunnyTarget: chooseKillerBunniesRoomUtilityBunnyTarget,
    chooseDefectorTarget: chooseKillerBunniesRoomDefectorTarget,
    discardDefectorDetector: discardKillerBunniesRoomDefectorDetector,
    resolveDefectorRoll: resolveKillerBunniesRoomDefectorRoll,
    callPovertyPoker: callKillerBunniesRoomPovertyPoker,
    antePovertyPoker: anteKillerBunniesRoomPovertyPoker,
    resolvePovertyPokerRoll: resolveKillerBunniesRoomPovertyPokerRoll,
    chooseCarrot: chooseKillerBunniesRoomCarrot,
    drawPile: drawKillerBunniesRoomPile,
    buyShopItem: buyKillerBunniesRoomShopItem,
    replaceRun: replaceKillerBunniesRoomRun,
    discardExtra: discardExtraKillerBunniesRoomCard,
  });
}
